[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openg2p-registry-celery-beat"
authors = [
  { name="OpenG2P", email="info@openg2p.org" },
]
description = "OpenG2P Registry Celery Beat Producers"
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
  "Operating System :: OS Independent",
]
dependencies = [
  "openg2p-fastapi-common",
  "celery",
  "redis",
  "psycopg2"
]
dynamic = ["version"]

[project.urls]
Homepage = "https://openg2p.org"
Documentation = "https://docs.openg2p.org/"
Repository = "https://github.com/OpenG2P/registry-platform"
Source = "https://github.com/OpenG2P/registry-platform"

[tool.hatch.version]
path = "src/openg2p_registry_celery_beat/__init__.py"
