class Workers:

    INGEST_DATA_CLASSIFICATION_WORKER = "ingest_data_classification_worker"
    INGEST_DATA_TRANSFORMATION_WORKER = "ingest_data_transformation_worker"
    OUTGEST_DATA_TRANSFORMATION_WORKER = "outgest_data_transformation_worker"
    INGEST_DATA_WORKER = "ingest_data_worker"
    CHANGE_REQUEST_INGEST_WORKER = "change_request_ingest_worker"
    OUTGEST_DATA_PUBLISH_WORKER = "outgest_data_publish_worker"
    OUTGEST_TOPIC_REGISTER_WORKER = "outgest_topic_register_worker"
    DEDUPLICATION_REGISTER_WORKER = "deduplication_register_worker"
    DEDUPLICATION_CHANGEREQUEST_WORKER = "deduplication_change_request_worker"
    INTAKE_FORM_REGISTER_INGEST_WORKER = "intake_form_register_ingest_worker"
    FUNCTIONAL_ID_ALLOCATION_WORKER = "functional_id_allocation_worker"
    FUNCTIONAL_ID_UPDATION_WORKER = "functional_id_updation_worker"
    SCORE_COMPUTE_WORKER = "score_compute_worker"
    COMPLETION_SCORE_WORKER = "completion_score_worker"
    DEDUPLICATION_INTAKE_FORMS_VS_REGISTER_WORKER = "deduplication_intake_forms_vs_register_worker"
    DEDUPLICATION_INTAKE_FORMS_VS_INTAKE_FORMS_WORKER = "deduplication_intake_forms_vs_intake_forms_worker"
    IMPORT_FILE_PROCESS_WORKER = "import_file_process_worker"
    REGISTER_EXPORT_WORKER = "register_export_worker"
